import urllib.request
import urllib.parse
import json
import time

TOKEN = "ghp_REMOVED_FOR_SECURITY"
REPO = "EDOHWARES/SoroMint"

def create_issue(title, body, labels):
    url = f"https://api.github.com/repos/{REPO}/issues"
    data = json.dumps({
        "title": title,
        "body": body,
        "labels": labels
    }).encode('utf-8')
    
    req = urllib.request.Request(url, data=data, method='POST')
    req.add_header("Authorization", f"token {TOKEN}")
    req.add_header("Accept", "application/vnd.github.v3+json")
    req.add_header("User-Agent", "SoroMint-Issue-Creator")
    req.add_header("Content-Type", "application/json")
    
    try:
        with urllib.request.urlopen(req) as response:
            if response.status == 201:
                print(f"✅ Successfully created issue: {title}", flush=True)
            else:
                print(f"⚠️ Failed to create issue: {title}. Status: {response.status}", flush=True)
    except Exception as e:
        print(f"❌ Error creating issue: {title}. Error: {str(e)}", flush=True)
    
    time.sleep(20) # Very safe delay to avoid secondary rate limits (20s)

backend_issues = [
    {"title": "Backend: Implement Redis-based Caching for Stream Balance Lookups", "body": "## Description\\nTo improve API response times and reduce load on the Soroban RPC server, we need to implement a Redis-based caching layer for stream balance queries.\\n\\n## Requirements\\n- Set up Redis connection in the backend.\\n- Cache balance results with a TTL (e.g., 5 seconds) as balances change per ledger.\\n- Invalidate cache when a withdraw or cancel operation is detected.\\n\\n## Acceptance Criteria\\n- Balance queries respond < 50ms from cache.\\n- Cache is properly invalidated on state changes.\\n- Fallback to RPC if Redis is unavailable.", "labels": ["area/backend", "priority/medium", "complexity/medium"]},
    {"title": "Backend: Add Global Rate Limiting for API Endpoints", "body": "## Description\\nProtect the backend from DDoS attacks and abusive clients by implementing rate limiting across all API routes.\\n\\n## Requirements\\n- Use `express-rate-limit`.\\n- Define different limits for read (GET) and write (POST/DELETE) operations.\\n- Return standard 429 status codes with Retry-After headers.\\n\\n## Acceptance Criteria\\n- API returns 429 after exceeding limits.\\n- Rate limits are configurable via environment variables.", "labels": ["area/backend", "priority/high", "complexity/low"]},
    {"title": "Backend: Implement Scalable Structured Logging with Winston", "body": "## Description\\nCurrent console.log statements are insufficient for production monitoring. We need structured JSON logging.\\n\\n## Requirements\\n- Integrate Winston.\\n- Log error, warn, info levels separately.\\n- Include request ID and timestamp in every log entry.\\n- Export logs to a file or external logging service.\\n\\n## Acceptance Criteria\\n- All logs follow a consistent JSON schema.\\n- Errors include stack traces.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: Automate MongoDB Backups to S3/Local Storage", "body": "## Description\\nEnsure data durability by setting up automated daily backups for the MongoDB database.\\n\\n## Requirements\\n- Create a cron job or worker service for backups.\\n- Upload backups to a secure location.\\n- Implement a retention policy (e.g., keep last 30 days).\\n\\n## Acceptance Criteria\\n- Backups are generated daily without manual intervention.\\n- Restoration script verified.", "labels": ["area/backend", "priority/high", "complexity/medium"]},
    {"title": "Backend: Implement Webhook System for Stream Life-cycle Events", "body": "## Description\\nAllow external services to react to stream events (created, withdrawn, canceled) via webhooks.\\n\\n## Requirements\\n- Create a webhook registration API.\\n- Implement a reliable delivery mechanism with retries.\\n- Sign webhook payloads for security.\\n\\n## Acceptance Criteria\\n- External endpoints receive POST notifications on stream events.\\n- Retry logic handles temporary failures.", "labels": ["area/backend", "priority/medium", "complexity/high"]},
    {"title": "Backend: Develop Admin Dashboard API for Platform Management", "body": "## Description\\nProvide administrative endpoints to monitor platform health and manage global configurations.\\n\\n## Requirements\\n- Endpoints for TVL (Total Value Locked) calculation.\\n- Endpoints to toggle maintenance mode.\\n- Endpoints for user management (ban/unban).\\n\\n## Acceptance Criteria\\n- Admins can retrieve system-wide metrics.\\n- All admin routes are protected by high-privilege JWTs.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: Multi-Network Support (Testnet vs Mainnet) Configuration", "body": "## Description\\nRefactor the backend to easily switch between different Stellar/Soroban networks.\\n\\n## Requirements\\n- Move network-specific constants to `.env`.\\n- Support multiple RPC URLs and Network Passphrases.\\n- Dynamic contract ID loading based on environment.\\n\\n## Acceptance Criteria\\n- Backend works seamlessly on Testnet and Mainnet with config changes.", "labels": ["area/backend", "priority/high", "complexity/low"]},
    {"title": "Backend: Enhance JWT Security with Refresh Tokens", "body": "## Description\\nCurrent JWT implementation only uses access tokens. Add refresh tokens for better security and UX.\\n\\n## Requirements\\n- Implement short-lived access tokens and long-lived refresh tokens.\\n- Store refresh token hashes in MongoDB.\\n- Add endpoint to rotate refresh tokens.\\n\\n## Acceptance Criteria\\n- Users stay logged in securely without re-entering credentials.\\n- Revoked tokens are properly handled.", "labels": ["area/backend", "priority/medium", "complexity/medium"]},
    {"title": "Backend: Comprehensive Unit Testing for Streaming Service", "body": "## Description\\nEnsure the core streaming service logic is robust through extensive unit testing.\\n\\n## Requirements\\n- Use Jest for testing.\\n- Mock Soroban RPC responses.\\n- Test edge cases: zero amounts, invalid IDs, network timeouts.\\n\\n## Acceptance Criteria\\n- Coverage for `streaming-service.js` > 90%.\\n- All tests pass in CI.", "labels": ["area/backend", "priority/high", "complexity/medium"]},
    {"title": "Backend: Integration Testing for Full Stream Creation Workflow", "body": "## Description\\nTest the entire flow from API request to database persistence and RPC simulation.\\n\\n## Requirements\\n- Use Supertest for API requests.\\n- Integrate with a test MongoDB instance.\\n- Simulate Soroban transaction success/failure.\\n\\n## Acceptance Criteria\\n- Verified end-to-end flow for `/api/v1/streams`.\\n- Concurrent requests handled correctly.", "labels": ["area/backend", "priority/high", "complexity/medium"]},
    {"title": "Backend: Email Notification Service for Stream Activity", "body": "## Description\\nNotify users via email when a stream is created for them or when they receive funds.\\n\\n## Requirements\\n- Integrate SendGrid or AWS SES.\\n- Create email templates for different events.\\n- Opt-in/out settings in user profile.\\n\\n## Acceptance Criteria\\n- Recipient receives email upon stream creation.\\n- Emails are sent asynchronously via a queue.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: Implement Paginated Stream History Endpoint", "body": "## Description\\nOptimized GET `/streams` to support pagination and filtering.\\n\\n## Requirements\\n- Use MongoDB `skip` and `limit`.\\n- Allow filtering by status, token, and date range.\\n- Return metadata (total count, next page).\\n\\n## Acceptance Criteria\\n- UI can efficiently browse thousands of streams.\\n- Filters work accurately.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: Real-time Analytics API for Platform TVL", "body": "## Description\\nCalculate and expose real-time metrics for Total Value Locked and active stream counts.\\n\\n## Requirements\\n- Aggregate balances across all active streams.\\n- Expose via `/api/v1/analytics`.\\n- Cache results to prevent heavy DB/RPC load.\\n\\n## Acceptance Criteria\\n- Dashboard updates with accurate TVL data.\\n- Response time < 100ms.", "labels": ["area/backend", "priority/medium", "complexity/medium"]},
    {"title": "Backend: Request Schema Validation using Zod/Joi", "body": "## Description\\nEnsure all incoming API requests strictly adhere to the expected format.\\n\\n## Requirements\\n- Implement middleware for Zod/Joi validation.\\n- Standardize error responses (400 Bad Request).\\n- Cover all POST/PUT routes.\\n\\n## Acceptance Criteria\\n- Malformed requests are rejected before hitting controllers.\\n- Informative error messages for developers.", "labels": ["area/backend", "priority/high", "complexity/low"]},
    {"title": "Backend: Health Check and Monitoring Endpoints", "body": "## Description\\nImplement standard `/health` and `/status` endpoints for load balancers and monitoring tools.\\n\\n## Requirements\\n- Check DB connectivity.\\n- Check Soroban RPC connectivity.\\n- Check current server load/memory.\\n\\n## Acceptance Criteria\\n- Monitoring tools can detect unhealthy instances instantly.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: GitHub Actions CI/CD Pipeline for Automatic Deployment", "body": "## Description\\nAutomate testing and deployment to staging/production environments.\\n\\n## Requirements\\n- Create `.github/workflows/main.yml`.\\n- Run linting and tests on PR.\\n- Deploy to Docker Hub / Cloud provider on merge.\\n\\n## Acceptance Criteria\\n- Code is automatically verified and deployed.\\n- Deployment notifications sent to Slack/Discord.", "labels": ["area/backend", "priority/high", "complexity/medium"]},
    {"title": "Backend: Optimize MongoDB Indexes for Frequent Queries", "body": "## Description\\nIdentify and implement missing indexes to speed up stream lookups.\\n\\n## Requirements\\n- Index `senderAddress`, `recipientAddress`.\\n- Compound index for `status` and `createdAt`.\\n- Analyze query performance with `EXPLAIN`.\\n\\n## Acceptance Criteria\\n- Query execution time reduced significantly for large datasets.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: Exponential Backoff Retry for Soroban RPC Failures", "body": "## Description\\nHandle transient network errors when interacting with Stellar/Soroban nodes.\\n\\n## Requirements\\n- Implement a retry strategy for all RPC calls.\\n- Use exponential backoff (1s, 2s, 4s...).\\n- Max retry count and alerting on permanent failure.\\n\\n## Acceptance Criteria\\n- Temporary RPC outages do not crash backend operations.\\n- Operations eventually succeed after node recovery.", "labels": ["area/backend", "priority/high", "complexity/medium"]},
    {"title": "Backend: Custom Metadata Support for Streams", "body": "## Description\\nAllow users to attach arbitrary JSON metadata to their streams (e.g., 'Project Name', 'Invoice ID').\\n\\n## Requirements\\n- Update MongoDB schema to include `metadata` field.\\n- Sanitize metadata input to prevent injection.\\n- Allow searching/filtering by metadata keys.\\n\\n## Acceptance Criteria\\n- Clients can track streams with their own context.\\n- UI displays custom metadata.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: Full-text Search for Streams by Metadata/Notes", "body": "## Description\\nImplement a powerful search interface for users to find their streams.\\n\\n## Requirements\\n- Use MongoDB Atlas Search or basic regex if appropriate.\\n- Search across sender, recipient, and metadata fields.\\n- Debounced search results API.\\n\\n## Acceptance Criteria\\n- Fast and accurate search results for users.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: CSV/JSON Export Feature for User Streams", "body": "## Description\\nAllow users to download their streaming history for accounting or tax purposes.\\n\\n## Requirements\\n- Endpoint to generate and stream CSV/JSON files.\\n- Support date range filters.\\n- Secure access (only own streams).\\n\\n## Acceptance Criteria\\n- Users can download a clean report of all transactions.", "labels": ["area/backend", "priority/low", "complexity/low"]},
    {"title": "Backend: API Latency Tracking and Performance Middleware", "body": "## Description\\nMeasure and log the time taken for each API request to identify bottlenecks.\\n\\n## Requirements\\n- Implement middleware to calculate request duration.\\n- Log duration alongside the route name.\\n- Integrate with Prometheus/Grafana if available.\\n\\n## Acceptance Criteria\\n- Detailed performance logs available for analysis.", "labels": ["area/backend", "priority/low", "complexity/low"]},
    {"title": "Backend: Off-chain Refund Logic for Failed Transactions", "body": "## Description\\nHandle edge cases where a transaction succeeds on-chain but fails to update the backend.\\n\\n## Requirements\\n- Reconciliation worker to compare DB vs Chain state.\\n- Automated fix-up or manual audit logs.\\n- Notify admin of discrepancies.\\n\\n## Acceptance Criteria\\n- DB and Chain are always in sync.\\n- No 'ghost' streams in the backend.", "labels": ["area/backend", "priority/high", "complexity/high"]},
    {"title": "Backend: Event Indexer Service for Historical Data Recovery", "body": "## Description\\nA standalone worker to scan historical ledgers and rebuild the database from events.\\n\\n## Requirements\\n- Fetch events using Soroban RPC `getEvents`.\\n- Idempotent processing to avoid duplicate entries.\\n- Configuration for start ledger.\\n\\n## Acceptance Criteria\\n- Database can be fully rebuilt from chain history.", "labels": ["area/backend", "priority/medium", "complexity/high"]},
    {"title": "Backend: BIP-39 Vault Service for Internal Management", "body": "## Description\\nSecurely manage platform-owned keys (for fees or automated tasks).\\n\\n## Requirements\\n- Use a secure enclave or environment variable vault.\\n- Support signing transactions internally for specific routes.\\n- Thoroughly audit key access.\\n\\n## Acceptance Criteria\\n- Platform can automate administrative tasks securely.", "labels": ["area/backend", "priority/high", "complexity/high"]},
    {"title": "Backend: Public Stream Discovery API", "body": "## Description\\nA feature to list all 'public' streams (e.g., for crowdfunding or public grants).\\n\\n## Requirements\\n- Add a `public` boolean to stream creation.\\n- API endpoint for public streams with featured sorting.\\n- Rate limit discovery calls.\\n\\n## Acceptance Criteria\\n- Public streams are visible to all users.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: WebSocket Integration for Real-time Status Updates", "body": "## Description\\nPush real-time updates to the frontend when a stream status changes.\\n\\n## Requirements\\n- Integrate Socket.io.\\n- Emit events on withdraw, cancel, or creation.\\n- Namespace by user address for security.\\n\\n## Acceptance Criteria\\n- Frontend updates instantly without polling.", "labels": ["area/backend", "priority/medium", "complexity/medium"]},
    {"title": "Backend: Basic Fraud Detection and Anomaly Monitoring", "body": "## Description\\nMonitor for suspicious activity like rapid stream-withdraw-cancel cycles.\\n\\n## Requirements\\n- Define anomaly patterns.\\n- Flag transactions for review.\\n- Alert admins via Discord/Slack.\\n\\n## Acceptance Criteria\\n- Potentially malicious activity is flagged immediately.", "labels": ["area/backend", "priority/low", "complexity/high"]},
    {"title": "Backend: Swagger/OpenAPI Documentation Implementation", "body": "## Description\\nGenerate and host interactive API documentation.\\n\\n## Requirements\\n- Use `swagger-jsdoc` and `swagger-ui-express`.\\n- Document all routes, parameters, and responses.\\n- Keep documentation in sync with Zod/Joi schemas.\\n\\n## Acceptance Criteria\\n- `/api-docs` provides a clear, interactive interface for developers.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: Internationalization (i18n) for API Error Messages", "body": "## Description\\nSupport multiple languages in error messages returned by the API.\\n\\n## Requirements\\n- Set up `i18next`.\\n- Translation files for English, Spanish, French, etc.\\n- Detect language from `Accept-Language` header.\\n\\n## Acceptance Criteria\\n- Global users receive errors in their preferred language.", "labels": ["area/backend", "priority/low", "complexity/low"]},
    {"title": "Backend: Platform Fee Collection Service", "body": "## Description\\nImplement the backend logic to track and collect platform fees.\\n\\n## Requirements\\n- Calculate fee during stream creation.\\n- Track fee payouts in DB.\\n- Endpoint for admins to withdraw collected fees.\\n\\n## Acceptance Criteria\\n- Fees are accurately tracked and manageable.", "labels": ["area/backend", "priority/medium", "complexity/medium"]},
    {"title": "Backend: Batch Stream Creation Support", "body": "## Description\\nAllow users to create multiple streams in a single API call (and ideally a single transaction).\\n\\n## Requirements\\n- Accept an array of stream configurations.\\n- Build a multi-invocation transaction.\\n- Handle partial successes/failures.\\n\\n## Acceptance Criteria\\n- Efficient creation of many streams for payroll-style use cases.", "labels": ["area/backend", "priority/high", "complexity/medium"]},
    {"title": "Backend: Transaction Simulation Service", "body": "## Description\\nProvide an endpoint to simulate transactions and return estimated gas usage and results.\\n\\n## Requirements\\n- Call `simulateTransaction` on Soroban RPC.\\n- Return costs in XLM.\\n- Useful for frontend UX (showing fees before signing).\\n\\n## Acceptance Criteria\\n- Clients can show accurate fee estimates.", "labels": ["area/backend", "priority/medium", "complexity/medium"]},
    {"title": "Backend: Dynamic Token Registry and Metadata Fetcher", "body": "## Description\\nKeep track of supported tokens and fetch their metadata (name, symbol, decimals).\\n\\n## Requirements\\n- Store token metadata in MongoDB.\\n- Fetch from chain once and cache.\\n- Expose via `/api/v1/tokens`.\\n\\n## Acceptance Criteria\\n- Frontend correctly displays token info for any address.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: Automated Load Testing Suite using K6", "body": "## Description\\nStress test the backend to find breaking points.\\n\\n## Requirements\\n- Create K6 scripts for common scenarios.\\n- Target concurrent stream creations and withdrawals.\\n- Benchmark throughput and latency.\\n\\n## Acceptance Criteria\\n- Performance baselines established.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: Soft Delete Implementation for Data Archiving", "body": "## Description\\nInstead of deleting records, mark them as hidden to preserve history.\\n\\n## Requirements\\n- Add `isArchived` or `deletedAt` fields.\\n- Update all queries to filter out archived records.\\n- Provide admin tool to restore data.\\n\\n## Acceptance Criteria\\n- Accidental deletions can be recovered.\\n- Data integrity maintained.", "labels": ["area/backend", "priority/medium", "complexity/low"]},
    {"title": "Backend: Soroban Gas Price Monitor and Alerting", "body": "## Description\\nMonitor the Stellar network for sudden spikes in gas/fee requirements.\\n\\n## Requirements\\n- Polling service for fee stats.\\n- Alert threshold configuration.\\n- Inform users via API if fees are too high.\\n\\n## Acceptance Criteria\\n- Admins and users are aware of network congestion.", "labels": ["area/backend", "priority/low", "complexity/low"]},
    {"title": "Backend: Scheduled Stream Execution Service", "body": "## Description\\nLogic to handle streams that should start at a future date/ledger.\\n\\n## Requirements\\n- Worker to monitor when scheduled streams should become active.\\n- Internal state transitions in DB.\\n- Notifications to users.\\n\\n## Acceptance Criteria\\n- Users can plan future payments.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: Referral and Rewards Tracking System Logic", "body": "## Description\\nTrack referrals when users invite others to the platform.\\n\\n## Requirements\\n- Referral code generation.\\n- Tracking which stream was created via which referral.\\n- Reward calculation logic.\\n\\n## Acceptance Criteria\\n- Operational basis for marketing campaigns.", "labels": ["area/backend", "priority/low", "complexity/medium"]},
    {"title": "Backend: Deep Benchmarking and Optimization Sprint", "body": "## Description\\nA dedicated task for profiling the server and optimizing hot code paths.\\n\\n## Requirements\\n- Use Node.js profiler or flame graphs.\\n- Optimize async operations.\\n- Reduce memory footprint.\\n\\n## Acceptance Criteria\\n- 20% improvement in general request handling.", "labels": ["area/backend", "priority/low", "complexity/medium"]}
]

contract_issues = [
    {"title": "Contract: WASM Binary Size Optimization Sprint", "body": "## Description\\nOptimize the streaming contract to minimize WASM size and reduce deployment/execution costs.\\n\\n## Requirements\\n- Review dependencies and remove unused features.\\n- Use compact Soroban data types.\\n- Apply `wasm-opt` or similar tools in build process.\\n\\n## Acceptance Criteria\\n- WASM size reduced by at least 15%.\\n- No loss in functionality.", "labels": ["area/contracts", "priority/high", "complexity/medium"]},
    {"title": "Contract: Implement Global 'Pause' Mechanism (Emergency Shutdown)", "body": "## Description\\nAdd ability for contract owner/DAO to pause state-changing operations in case of an exploit.\\n\\n## Requirements\\n- Define `Admin` storage key.\\n- Add `pause` and `unpause` functions.\\n- Wrap `create`, `withdraw`, `cancel` with check for pause state.\\n\\n## Acceptance Criteria\\n- Operations are blocked when paused.\\n- Only authorized address can toggle pause.", "labels": ["area/contracts", "priority/high", "complexity/low"]},
    {"title": "Contract: Support for Capped Streams (Max Total Value)", "body": "## Description\\nRestrict stream creation to a maximum amount for risk management.\\n\\n## Requirements\\n- Global limit configurable by admin.\\n- Check amount in `create_stream`.", "labels": ["area/contracts", "priority/medium", "complexity/low"]},
    {"title": "Contract: Multi-recipient Stream Implementation", "body": "## Description\\nAllow creating one stream that distributes to multiple recipients proportionally.\\n\\n## Requirements\\n- Data structure to store multiple recipients and their weights.\\n- Update `withdraw` logic to use weights.\\n\\n## Acceptance Criteria\\n- Efficient one-to-many streaming payments.", "labels": ["area/contracts", "priority/medium", "complexity/high"]},
    {"title": "Contract: Advanced Storage Lease Management (TTL)", "body": "## Description\\nImplement automatic or manual TTL extension for stream records to prevent data deletion.\\n\\n## Requirements\\n- Use `env.storage().persistent().extend_ttl()`.\\n- Calculate extension based on stream duration.\\n\\n## Acceptance Criteria\\n- Active streams never 'expire' from network storage.", "labels": ["area/contracts", "priority/high", "complexity/medium"]},
    {"title": "Contract: Governance-controlled Fee Collection Logic", "body": "## Description\\nAllow a portion of each stream to be collected as a platform fee.\\n\\n## Requirements\\n- DAO-configurable fee percentage.\\n- Deduct fee in `create_stream` or `withdraw`.\\n- Separate vault/balance for collected fees.\\n\\n## Acceptance Criteria\\n- Fees are collected and withdrawable by the treasury.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Upgradable Proxy Pattern Support", "body": "## Description\\nImplement the standard Soroban upgradability pattern to allow logic updates.\\n\\n## Requirements\\n- Implement `upgrade` function controlled by admin.\\n- Use `env.deployer()`.\\n\\n## Acceptance Criteria\\n- Contract code can be updated without losing state.", "labels": ["area/contracts", "priority/high", "complexity/medium"]},
    {"title": "Contract: Support for Soroban 'Permit' Style Token Transfers", "body": "## Description\\nImplement or integrate with Permit logic to allow one-click stream creation (no separate 'approve' transaction).\\n\\n## Requirements\\n- Check for EIP-2612 style support in Soroban SAC.\\n- Use signed authorization payloads in `create_stream`.\\n\\n## Acceptance Criteria\\n- Better user experience via signature-based auth.", "labels": ["area/contracts", "priority/medium", "complexity/high"]},
    {"title": "Contract: Stream Management Delegation (Operator Role)", "body": "## Description\\nAllow users to delegate 'cancel' or 'withdraw' permissions to another address.\\n\\n## Requirements\\n- Store operator address in stream data.\\n- Update `require_auth` logic.\\n\\n## Acceptance Criteria\\n- Third-party tools can bridge/manage user streams with permission.", "labels": ["area/contracts", "priority/low", "complexity/medium"]},
    {"title": "Contract: Clawback Implementation for Regulatory Compliance", "body": "## Description\\nAllow designated authorities to claw back funds in specific legal scenarios.\\n\\n## Requirements\\n- Only executable by specific 'Clawback Admin'.\\n- Emits clear 'Clawback' event.\\n\\n## Acceptance Criteria\\n- Compliant with financial regulations where required.", "labels": ["area/contracts", "priority/low", "complexity/medium"]},
    {"title": "Contract: Support for Non-linear Vesting Schedules", "body": "## Description\\nExpand beyond linear streaming to support cliffs and tiered release schedules.\\n\\n## Requirements\\n- Data structure to define 'milestones'.\\n- Logic in `balance_of` to handle jump-ahead releases.\\n\\n## Acceptance Criteria\\n- Complex vesting contracts can be built on SoroMint.", "labels": ["area/contracts", "priority/medium", "complexity/high"]},
    {"title": "Contract: Robust Math and Overflow Prevention Audit", "body": "## Description\\nDedicated review of all i128 math to ensure safety against edge-case overflows.\\n\\n## Requirements\\n- Use checked math everywhere (`checked_add`, `checked_mul`).\\n- Panic with descriptive errors on overflow.\\n\\n## Acceptance Criteria\\n- Mathematically sound contract behavior.", "labels": ["area/contracts", "priority/high", "complexity/medium"]},
    {"title": "Contract: Emergency 'Rug-Pull' Protection for Recipients", "body": "## Description\\nPrevent senders from canceling streams maliciously right before a withdrawal if specific conditions are met.\\n\\n## Requirements\\n- Configurable 'Cancellation Delay' or 'Irrevocable' flag.\\n\\n## Acceptance Criteria\\n- Increased trust for recipients.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Mandatory Event Logging for Every State Change", "body": "## Description\\nEnsure full transparency by emitting events for every storage write.\\n\\n## Requirements\\n- Review `update`, `create`, `delete` operations.\\n- Ensure all relevant data is in the event.\\n\\n## Acceptance Criteria\\n- Off-chain indexers can track 100% of state changes.", "labels": ["area/contracts", "priority/high", "complexity/low"]},
    {"title": "Contract: Metadata Specification Implementation", "body": "## Description\\nAdhere to Soroban contract metadata standards for better ecosystem compatibility.\\n\\n## Requirements\\n- Implement metadata traits.\\n- Include logo URL, description, and version.\\n\\n## Acceptance Criteria\\n- Contract details show up correctly in explorers.", "labels": ["area/contracts", "priority/low", "complexity/low"]},
    {"title": "Contract: Reentrancy Guard Protection Strategy", "body": "## Description\\nAdd protection against reentrancy attacks, especially for cross-contract calls.\\n\\n## Requirements\\n- Basic mutex implementation for state-changing functions.\\n\\n## Acceptance Criteria\\n- Secure against known smart contract attack vectors.", "labels": ["area/contracts", "priority/high", "complexity/medium"]},
    {"title": "Contract: Batch Withdrawal Logic and Efficiency", "body": "## Description\\nAllow a recipient to withdraw from multiple streams in a single transaction.\\n\\n## Requirements\\n- Optimized loop over stream IDs.\\n- Shared authorization check.\\n\\n## Acceptance Criteria\\n- Lower gas fees for power users.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Transferable Stream Ownership", "body": "## Description\\nAllow a sender to transfer their role (and refund rights) to another address.\\n\\n## Requirements\\n- `transfer_sender` function.\\n- Update storage keys.\\n\\n## Acceptance Criteria\\n- Streams can be 'sold' or transferred between accounts.", "labels": ["area/contracts", "priority/low", "complexity/medium"]},
    {"title": "Contract: Dynamic Rate Adjustment via Governance", "body": "## Description\\nAllow active streams to have their rates adjusted if both parties agree or via DAO rules.\\n\\n## Requirements\\n- Logic to recalculate based on remaining balance and new end time.\\n\\n## Acceptance Criteria\\n- Flexible streaming terms.", "labels": ["area/contracts", "priority/low", "complexity/high"]},
    {"title": "Contract: Support for Minimum and Maximum Stream Durations", "body": "## Description\\nEnforce platform rules on stream lengths.\\n\\n## Requirements\\n- Configurable range (e.g., 1 hour to 5 years).\\n\\n## Acceptance Criteria\\n- Prevents weird edge cases or spam streams.", "labels": ["area/contracts", "priority/low", "complexity/low"]},
    {"title": "Contract: Optimized Authorization and Signature Verification", "body": "## Description\\nProfile gas usage of `require_auth` and seek optimizations.\\n\\n## Requirements\\n- Compare different auth patterns in Soroban.\\n\\n## Acceptance Criteria\\n- Cheapest possible secure authentication.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Whitelisted Token Assets Logic", "body": "## Description\\nRestrict streaming to specific high-quality tokens (stablecoins, platform tokens).\\n\\n## Requirements\\n- Admin-managed whitelist storage.\\n- Check token in `create_stream`.", "labels": ["area/contracts", "priority/medium", "complexity/low"]},
    {"title": "Contract: Stream Extension and Top-up Logic", "body": "## Description\\nAllow adding more funds to an active stream to extend its life.\\n\\n## Requirements\\n- `extend_stream` function.\\n- Transfer additional tokens and update stop ledger.\\n\\n## Acceptance Criteria\\n- Seamless continuation of recurring payments.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Price Oracle Integration for Stable Value Streaming", "body": "## Description\\nStream a specific USD value of tokens per ledger using a price oracle.\\n\\n## Requirements\\n- Integrate with standard Soroban Oracles.\\n- Recalculate rate based on price feed.\\n\\n## Acceptance Criteria\\n- Recipients get stable value regardless of token volatility.", "labels": ["area/contracts", "priority/low", "complexity/high"]},
    {"title": "Contract: Privacy-preserving Stream Stub", "body": "## Description\\nResearch and implement a basic stub for private stream amounts using zero-knowledge.\\n\\n## Requirements\\n- Investigation into current Soroban ZK capabilities.\\n\\n## Acceptance Criteria\\n- Roadmap for privacy features.", "labels": ["area/contracts", "priority/low", "complexity/high"]},
    {"title": "Contract: Optimized Event Payload and Storage Layout", "body": "## Description\\nRe-organize data structures to minimize the 'dirtied' storage in a single TX.\\n\\n## Requirements\\n- Bundle related fields into single storage segments.\\n\\n## Acceptance Criteria\\n- Significant reduction in storage fees per stream.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Self-Destruct or Migration Cleanup Routine", "body": "## Description\\nAllow the contract to be retired safely, ensuring all funds are returned.\\n\\n## Requirements\\n- Clear instructions and safeguards.\\n\\n## Acceptance Criteria\\n- Clean decommissioning path.", "labels": ["area/contracts", "priority/low", "complexity/medium"]},
    {"title": "Contract: Complex Governance (Weighted Voting) Integration", "body": "## Description\\nSupport governance decisions based on token holdings or contribution history.\\n\\n## Requirements\\n- Integration with DAO module for parameter tuning.\\n\\n## Acceptance Criteria\\n- Truly decentralized platform management.", "labels": ["area/contracts", "priority/medium", "complexity/high"]},
    {"title": "Contract: Multi-sig Execution for Critical Functions", "body": "## Description\\nRequire multiple signatures for high-risk admin tasks (e.g., withdrawing fees).\\n\\n## Requirements\\n- Use `require_auth` with multi-signature support or custom logic.\\n\\n## Acceptance Criteria\\n- No single point of failure for treasury.", "labels": ["area/contracts", "priority/high", "complexity/medium"]},
    {"title": "Contract: WASM Memory Layout Optimization", "body": "## Description\\nFine-tune memory allocation to squeeze performance out of the WASM environment.\\n\\n## Requirements\\n- Profiling memory usage during execution.\\n\\n## Acceptance Criteria\\n- Faster execution times.", "labels": ["area/contracts", "priority/low", "complexity/high"]},
    {"title": "Contract: Full Integration Test Suite (Cross-Contract)", "body": "## Description\\nTest interactions between streaming, token, and governance contracts.\\n\\n## Requirements\\n- Use `soroban-test` or custom runner.\\n\\n## Acceptance Criteria\\n- System-wide stability verified.", "labels": ["area/contracts", "priority/high", "complexity/high"]},
    {"title": "Contract: Proof of Reserve Mechanism for Vaults", "body": "## Description\\nExpose functions that allow anyone to verify that the vault holds enough tokens.\\n\\n## Requirements\\n- Public view functions for balance vs liability.\\n\\n## Acceptance Criteria\\n- Transparency for all platform participants.", "labels": ["area/contracts", "priority/medium", "complexity/medium"]},
    {"title": "Contract: Hierarchical Deterministic Key Schema", "body": "## Description\\nOrganize storage keys into a clear, searchable hierarchy.\\n\\n## Requirements\\n- Use standard enum/tuple patterns for keys.\\n\\n## Acceptance Criteria\\n- Cleaner code and easier off-chain indexing.", "labels": ["area/contracts", "priority/low", "complexity/low"]},
    {"title": "Contract: Security Audit Remediation Workflow", "body": "## Description\\nEstablish a process for fast-tracking fixes found during professional audits.\\n\\n## Requirements\\n- Dummy issue to track the 'Security First' mindset.\\n\\n## Acceptance Criteria\\n- Process defined and ready for mainnet deployment.", "labels": ["area/contracts", "priority/high", "complexity/low"]},
    {"title": "Contract: Final Documentation and Public API Spec", "body": "## Description\\nCreate a human-readable guide for all contract functions.\\n\\n## Requirements\\n- README in contract folder.\\n- Doxygen style comments.\\n\\n## Acceptance Criteria\\n- Developers can easily build on top of our contracts.", "labels": ["area/contracts", "priority/medium", "complexity/low"]}
]

def main():
    # Detect already created issues to avoid duplicates
    # Since I'm starting fresh with a clean script, I'll allow resuming.
    # Currently created in previous runs (based on log):
    # Backend 0-11 were created.
    # Backend 13-14 were created.
    # So skip indices: 0,1,2,3,4,5,6,7,8,9,10,11, 13, 14
    skip_indices = {0,1,2,3,4,5,6,7,8,9,10,11,13,14}
    
    print(f"Resuming issue creation. Skipping indices: {skip_indices}", flush=True)
    
    print(f"Creating missing backend issues...", flush=True)
    for i in range(len(backend_issues)):
        if i in skip_indices:
            continue
        issue = backend_issues[i]
        create_issue(issue["title"], issue["body"], issue["labels"])
    
    print(f"Creating all contract issues...", flush=True)
    for issue in contract_issues:
        create_issue(issue["title"], issue["body"], issue["labels"])
    
    print("All tasks completed!", flush=True)

if __name__ == "__main__":
    main()
