global:
  scrape_interval: 15s
scrape_configs:
  - job_name: soromint-server
    metrics_path: /metrics
    basic_auth:
      username: prometheus
      password: soromint-metrics
    static_configs:
      - targets: [server:5000]
