name: Backend Lint & Format Check

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main
      - 'feature/**'
      - 'test/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./server

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'
          cache: 'pnpm'
          cache-dependency-path: |
            server/pnpm-lock.yaml
            client/pnpm-lock.yaml
          

      - name: Install Dependencies
        run: pnpm install

      - name: Run ESLint
        run: npm run lint

      - name: Check Prettier Formatting
        run: npm run format